name       : maelstrom
version    : 3.0.6
release    : 1
source     :
    - https://www.libsdl.org/projects/Maelstrom/src/Maelstrom-3.0.6.tar.gz : e7983c2c7376cdcca1944db1706d92aedd529638cf13358c88a60df982ba7b46
license    :
    - GPL-2.0
    - CC-By-3.0
component  : games.arcade
summary    : Pseudo-3D-rendered Asteroids clone
description: |
    Pseudo-3D-rendered Asteroids clone
builddeps  :
    - pkgconfig(SDL_net)
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm00644 $pkgfiles/usr/share/Maelstrom/
    install -Dm00644 $pkgfiles/Maelstrom.desktop $installdir/usr/share/applications/Maelstrom.desktop
    install -Dm00644 $pkgfiles/maelstrom.png $installdir/usr/share/pixmaps/maelstrom.png
